### ISSUE TITLE
move not using branch delay slot

### ISSUE THREAD

**Issue by jonwoodruff** [CTSRD-CHERI/llvm#248]
int * __capability test(int * __capability inCap, int test, int inInt)
{
  int * __capability ret = inCap;
  if (test) {
    ret+=inInt+4;
  }
  return ret;
}

Function starts with:
"
	move	 $fp, $sp
	beqz	$4, .LBB0_2
	nop
"
But should produce:
"
	beqz	$4, .LBB0_2
	move	 $fp, $sp
"

**Comment by davidchisnall** [comment]
Was this fixed by the big bunch of changes that stopped treating most CHERI instructions as having unmodeled side effects?

**Comment by jonwoodruff** [comment]
So things have moved along, but right now we're still not using the branch delay slot.  The assembly we're generating now is:

	cincoffset	$c24, $c11, $zero
	clc	$c3, $zero, 0($c3)
	beqz	$4, .LBB0_2
	nop

And it looks like either the cincoffset or the clc could be moved into the delay slot here.
